[[material]]
name = "plane_material"
color = [100, 100, 100]
diffuse = 0.7
specular = 0.0
glossiness = 0.0
reflectivity = 0.0

[[material]]
name = "green_material"
color = [0, 255, 0]
diffuse = 0.7
specular = 0.0
glossiness = 0.0
reflectivity = 0.0

[[material]]
name = "sphere_material"
color = [0, 0, 255]
diffuse = 0.3
specular = 0.2
glossiness = 20.0
reflectivity = 0.0

[scene]
ambient_const = 0.1
ambient_color = [255, 255, 255]

[scene.camera]
pos = [0.0, 1.0, -7.0]
#lookat = [3.0, 3.0, -4.0]
lookat = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]

[[scene.surface]]
type = "sphere"
material = "sphere_material"
pos = [0.0, 1.0, 0.0]
radius = 1.0

[[scene.surface]]
type = "plane"
material = "green_material"
pos = [0.0, 0.0, 2.0]
normal = [0.0, 0.0, -1.0]

[[scene.surface]]
type = "plane"
material = "green_material"
pos = [3.5, 0.0, 0.0]
normal = [-1.0, 0.0, 0.0]

[[scene.surface]]
type = "plane"
material = "plane_material"
pos = [0.0, 0.0, 0.0]
normal = [0.0, 1.0, 0.0]

[[scene.surface]]
type = "plane"
material = "plane_material"
pos = [-3.5, 0.0, 0.0]
normal = [1.0, 0.0, 0.0]

[[scene.light]]
type = "point"
pos = [2.0, 3.0, -4.0]
color = [255, 255, 255]
intensity = 2.0
